# Generated by Django 5.1.3 on 2024-11-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0003_category_created_on_recipe_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
